name: CodeReview

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get git diff
        run: |
          git fetch origin
          git diff --unified=0 ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > diff.txt
          echo "DIFF_CONTENT<<EOF" >> $GITHUB_ENV
          cat diff.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Request review from Ollama
        run: |
          ESCAPED_DIFF=$(echo "$DIFF_CONTENT" | jq -sRr @json)

          PROMPT=$(jq -n --arg diff "$ESCAPED_DIFF" '
          "You are a senior software engineer reviewing the following code diff.

Please analyze it and respond with JSON only, using this exact structure:

[
  {
    \"path\": \"<file_path>\",
    \"line\": <line_number>,
    \"text\": \"<concise review comment>\",
    \"side\": \"RIGHT\"
  }
]

Here is the git diff:
\($diff)"
          ')

          REQUEST_BODY=$(jq -n \
            --arg model "${{ secrets.REVIEW_MODEL_NAME }}" \
            --arg prompt "$PROMPT" \
            '{model: $model, prompt: $prompt, stream: false}')

          RESPONSE=$(curl -s -X POST ${{ secrets.REVIEW_API_URL }} \
            -H "Content-Type: application/json" \
            -d "$REQUEST_BODY" | jq -r .response)

          echo "$RESPONSE" > res.txt

      - name: Clean and parse LLM output
        id: parse
        run: |
          sed '/^```/d' res.txt > cleaned.txt
          COMMENT_JSON=$(cat cleaned.txt | jq -c .)
          echo "comments=${COMMENT_JSON}" >> $GITHUB_OUTPUT

      - name: Post line-by-line comments to PR
        uses: nbaztec/add-pr-review-comment@v1.0.7
        with:
          comments: ${{ steps.parse.outputs.comments }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'